Vue  = require('vue').default
Vuex = require('vuex')

Vue.use(Vuex)

module.exports = new Vuex.Store({

  strict: process.env.NODE_ENV isnt 'production'

  modules:
    'account':                      require('./account')
    'admin-forums':                 require('./admin-forums')
    'admin-sync':                   require('./admin-sync')
    'bus':                          require('./bus')
    'comment-modal':                require('./comment-modal')
    'forum-banner-modal':           require('./forum-banner-modal')
    'forum-face-modal':             require('./forum-face-modal')
    'forum-managers-modal':         require('./forum-managers-modal')
    'confirm':                      require('./confirm')
    'create-forum-modal':           require('./create-forum-modal')
    'create-organization-modal':    require('./create-organization-modal')
    'create-person-modal':          require('./create-person-modal')
    'create-role-modal':            require('./create-role-modal')
    'create-subject-modal':         require('./create-subject-modal')
    'edit-organization-base-modal': require('./edit-organization-base-modal')
    'edit-person-base-modal':       require('./edit-person-base-modal')
    'edit-role-base-modal':         require('./edit-role-base-modal')
    'edit-subject-base-modal':      require('./edit-subject-base-modal')
    'edit-subject-casts-modal':     require('./edit-subject-casts-modal')
    'edit-subject-episodes-modal':  require('./edit-subject-episodes-modal')
    'edit-subject-resources-modal': require('./edit-subject-resources-modal')
    'edit-subject-staffs-modal':    require('./edit-subject-staffs-modal')
    'input-content':                require('./input-content')
    'mark-modal':                   require('./mark-modal')
    'move-post-modal':              require('./move-post-modal')
    'notify':                       require('./notify')
    'post-detail':                  require('./post-detail')
    'post-list':                    require('./post-list')
    'post-modal':                   require('./post-modal')
    'prompt':                       require('./prompt')
    'public-timeline':              require('./public-timeline')
    'reference-comment-modal':      require('./reference-comment-modal')
    'reminder':                     require('./reminder')
    'router':                       require('./router')
    'search-modal':                 require('./search-modal')
    'setting':                      require('./setting')
    'toast':                        require('./toast')
    'totoro':                       require('./totoro')
    'update-forum-modal':           require('./update-forum-modal')
    'user-banner-modal':            require('./user-banner-modal')
    'user-detail':                  require('./user-detail')
    'user-face-modal':              require('./user-face-modal')
    'wiki-face-modal':              require('./wiki-face-modal')
})